---
# tasks file for ./roles/irmc_account_admin
- name: Define a new *SECRET* parameter from vars and defaults
  ansible.builtin.set_fact:
    new_user_password: "{{ password }}"
  no_log: true # Always true because it contains Secret.
  tags: always
  when: password is defined

- name: Change admin configurations
  fujitsu.primergy.irmc_user:
    irmc_url: "{{ inventory_hostname }}"
    irmc_username: "{{ irmc_user }}"
    irmc_password: "{{ irmc_password }}"
    validate_certs: "{{ validate_certificate }}"
    command: change
    name: admin
    password: "{{ new_user_password | default(omit) }}"
    description: "{{ description | default(omit) }}"
    redfish_enabled: "{{ access.redfish.enable | default(omit) }}"
    redfish_role: "{{ access.redfish.role | default(omit) }}"
    lan_privilege: "{{ access.ipmi.lan_privilege | default(omit) }}"
    serial_privilege: "{{ access.ipmi.serial_privilege | default(omit) }}"
    config_user_enabled: "{{ access.ipmi.enable_user_account_conf | default(omit) }}"
    config_bmc_enabled: "{{ access.ipmi.enable_irmc_settings_conf | default(omit) }}"
    avr_enabled: "{{ access.avr.enable_avr | default(omit) }}"
    storage_enabled: "{{ access.avr.enable_remote_storage | default(omit) }}"
    snmpv3_enabled: "{{ snmpv3.enable | default(omit) }}"
    email_enabled: "{{ email.general.enable | default(omit) }}"
    email_type: "{{ email.general.format | default(omit) }}"
    email_server: "{{ email.general.server | default(omit) }}"
    email_address: "{{ email.general.address | default(omit) }}"
    alert_fans: "{{ email.alert.fan | default(omit) }}"
    alert_temperatures: "{{ email.alert.temperature | default(omit) }}"
    alert_hwerrors: "{{ email.alert.hardware_error | default(omit) }}"
    alert_syshang: "{{ email.alert.system_hang | default(omit) }}"
    alert_posterrors: "{{ email.alert.post_error | default(omit) }}"
    alert_security: "{{ email.alert.security | default(omit) }}"
    alert_sysstatus: "{{ email.alert.status | default(omit) }}"
    alert_hderrors: "{{ email.alert.disk | default(omit) }}"
    alert_network: "{{ email.alert.network | default(omit) }}"
    alert_remote: "{{ email.alert.remote | default(omit) }}"
    alert_power: "{{ email.alert.power | default(omit) }}"
    alert_memory: "{{ email.alert.memory | default(omit) }}"
    alert_others: "{{ email.alert.other | default(omit) }}"
  delegate_to: localhost
