# See https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#configuration
config:
  no-inline-html: false  # MD033 - Inline HTML
  no-duplicate-heading: false  # MD024 - Multiple headings with the same content
