namespace: fujitsu
name: primergy
version: 2.0.1
readme: README.md
description: Ansible iRMC Collection for PRIMERGY Distribution by Fsas Technologies Inc..
repository: https://github.com/fujitsu/fujitsu-ansible-irmc-integration

authors:
  - Shinya Hamano <hamano.shinya@fujitsu.com>
  - Yutaka Kamioka <yutaka.kamioka@fujitsu.com>
  - Jiajun Guo <guo.jiajun@fujitsu.com>
  - Tomohisa Nakai <nakai.tomohisa@fujitsu.com>

license:
  - GPL-3.0-or-later

tags:
  - fujitsu
  - primergy
  - irmc
  - fti
  - infrastructure
  - windows
  - tools

build_ignore:
  - examples
  - group_vars
  - host_vars
  - tests
  - inventory.ini
  - ansible.cfg
  - .gitignore
  - .editorconfig
  - pyproject.toml
  - requirements.lock
  - requirements-dev.lock
  - .python-version
  - .venv
  - .ruff_cache
  - .ansible-lint
  - .markdownlint-cli2.yaml
