namespace: fujitsu

name: primergy

version: 1.0.0

readme: README.md

authors:
- Shinya Hamano <hamano.shinya@fujitsu.com>
- Yutaka Kamioka <yutaka.kamioka@fujitsu.com>
- Jiajun Guo <guo.jiajun@fujitsu.com>
- Tomohisa Nakai <nakai.tomohisa@fujitsu.com>

description: Ansible iRMC Collection for PRIMERGY Distribution by Fsas Technologies Inc..

license:
- GPL-3.0-or-later

tags: [fujitsu, primergy, irmc, fti]

repository: https://github.com/fujitsu/fujitsu-ansible-irmc-integration

build_ignore: ['examples', 'group_vars', 'tests', 'inventory.ini', 'ansible.cfg', '.gitignore', '.editorconfig', 'pyproject.toml', 'requirements.lock', 'requirements-dev.lock', '.python-version', '.venv', '.ruff_cache']
