namespace: fujitsu
name: ansible
version: 1.3.0
readme: README.md
authors:
  - [Nakamura Takayuki] (https://github.com/nakamura-taka)

description: Fujitsu iRMC Ansible Modules allows data center and IT
  administrators to use RedHat Ansible to automate and orchestrate the
  configuration, deployment, and update of Fujitsu PRIMERY servers.

license_file: LICENSE

tags:
  [
    "fujitsu",
    "fujitsuirmc",
    "infrastructure",
    "irmc",
    "openmanage_enterprise",
    "redfish",
    "redfish_api",
    "fujitsu_servers",
    "primery",
    "primery_server",
    "automation",
    "devops",
  ]


repository: https://github.com/fujitsu/fujitsu-ansible-irmc-integration

homepage: https://github.com/fujitsu

issues: https://github.com/fujitsu/fujitsu-ansible-irmc-integration/issues

documentation: https://github.com/fujitsu/fujitsu-ansible-irmc-integration/blob/master/DOCUMENTATION.md
