---
# iRMC設定
- name: Configure iRMC
  hosts: iRMC_group
  connection: local
  gather_facts: false
  tasks:
    # ローカルユーザアカウント設定
    - name: Configure admin account
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_account_admin
      vars:
        description: my description
        access:
          redfish:
            enable: true
            role: Administrator
          ipmi:
            lan_privilege: OEM
            serial_privilege: Administrator
            enable_user_account_conf: true
            enable_irmc_settings_conf: true
          avr:
            enable_avr: true

    # SSL証明書・CA証明書の登録
    - name: Register SSL certificate and CA certificate
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_set_certificate
      vars:
        ssl_private_key_path: "/path/to/certs/server.key"
        ssl_cert_path: "/path/to/certs/server.crt"
        ssl_ca_cert_path: "/path/to/certs/ca.crt"

    # SNMP設定
    - name: Set SNMP
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_snmp
      vars:
        snmp:
          enabled: true
          protocol: All
          community_name: public
        snmp_trap_destination:
          community_name: public
          servers:
            - index: 0
              name: 192.0.2.1
              protocol: SnmpV1

    # Eメール警告送信設定
    - name: Configure E-mail Alerting
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_email_alert
      vars:
        email_alert:
          enabled: true
        smtp:
          primary_server:
            address: smtp.mycompany.example.com
            authentication:
              type: Smtp
              username: AuthUserName
              password: AuthPassword
        email_format:
          from: MailFrom@mycompany.example.com
          subject: FixedMailSubject
          message: FixedMailMessage

    # 時刻同期設定
    - name: Configure time syncronization
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_set_ntp
      vars:
        ntp_server_primary: ntp1.mycompany.example.com
        ntp_server_secondary: ntp2.mycompany.example.com
        time_mode: System RTC
        time_zone_location: Asia/Tokyo
        rtc_mode: local time

    # ライセンス設定
    - name: Register and activate license keys
      ansible.builtin.include_role:
        name: fujitsu.primergy.irmc_set_license
      # NOTE: The 'license_keys' variable should be defined in the 'host_vars' file for each host.
      # Example:
      #   host_vars/<ipaddress-of-irmc>.yml:
      #     license_keys:
      #       - LICENSE-KEY1
      #       - LICENSE-KEY2
      # This ensures that each host gets the correct license keys for registration.

  post_tasks:
    # iRMC経由でPRIMERGYの電源オン
    - name: Turn ON the server
      fujitsu.primergy.irmc_powerstate:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: set
        state: PowerOn

# 電源投入後、Ansibleで操作可能になるまで待機
- name: Wait for Windows node to become available
  hosts: windows
  gather_facts: false
  tasks:
    - name: Wait for WinRM port to become available on the target Windows node
      ansible.builtin.wait_for_connection:
        timeout: 900  # 900 seconds = 15 minutes

# Windowsサーバー設定
- name: Configure Windows Server
  hosts: windows
  gather_facts: true
  tasks:
    # DNS設定
    - name: Set DNS
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_dns
      vars:
        adapter_names: "*"
        ipv4_addresses:
          # When joining a Windows domain, specify a primary DNS server that is associated with the domain controller:
          - 192.0.2.3
          - 192.0.2.4

    # データドライブ割り当て
    - name: Assign data drive
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_data_drive
      vars:
        drive_letter: D
        disk_number: 0
        op: create

    # 組織名と名前の設定
    - name: Set organization and owner
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_organization_owner
      vars:
        description: This is my Windows Server.
        organization: MyCompany Inc.
        owner: MyName

    # ホスト名変更
    - name: Set hostname
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_hostname
      vars:
        hostname: myhostname

    # 言語・地域・タイムゾーン設定
    - name: Set locale, region and timezone
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_locale
      vars:
        language: ja-JP
        location: 122
        timezone: Tokyo Standard Time

    # Windowsドメインへの参加
    - name: Join windows domain
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_set_membership
      vars:
        state: domain
        domain: ansible.mycompany.local
        username: ANSIBLE\Administrator
        password: P@ssw0rd

    # SNMP設定
    - name: Set SNMP
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_snmp
      vars:
        agent:
          contact: MyContact
          location: MyLocation
          service: 76
        security:
          accepted_community: public
          accepted_community_permission: 8
          send_auth_trap: true
        trap:
          community: public
          destination: 192.0.2.1

    # リモートデスクトップの有効化
    - name: Enable Remote Desktop
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_set_rdp
      vars:
        enabled: true

    # ServerView Agentsのセットアップ
    - name: Setup ServerView Agents
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_serverview_agents
      vars:
        password: User001
        installer: "/path/to/installer/ServerViewAgents_Win_x64.exe"

    # ServerView RAID Managerのセットアップ
    - name: Setup ServerView RAID Manager
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_serverview_raidmanager
      vars:
        password: User002
        installer: "/path/to/installer/ServerView_RAID_x64.exe"
        openjdk_installer: "/path/to/installer/OpenJDK8U-jre_x64_windows_hotspot.msi"

    # DSNAPのセットアップ
    - name: Setup DSNAP
      ansible.builtin.include_role:
        name: fujitsu.primergy.win_dsnap
      vars:
        language: Japanese
        path: "/path/to/iso/SVS15.24.06.03.iso"
