---
# tasks file for ./roles/irmc_snmp

- name: Generate SNMP settings as IRMC profile
  ansible.builtin.set_fact:
    snmp_profile: "{{ vars | fujitsu.primergy.snmp_profile_filter }}"
  tags: json

- name: Apply SNMP settings as IRMC profile
  fujitsu.primergy.irmc_profiles:
    irmc_url: "{{ inventory_hostname }}"
    irmc_username: "{{ irmc_user }}"
    irmc_password: "{{ irmc_password }}"
    validate_certs: "{{ validate_certificate }}"
    command: "import"
    profile_json: "{{ snmp_profile | to_json }}"
