---
# tasks file for ./roles/win_hostname
- name: Change the hostname
  ansible.windows.win_hostname:
    name: "{{ hostname }}"
  register: change_hostname

- name: Reboot
  ansible.windows.win_reboot:
  when: change_hostname.reboot_required
