---
# Copyright 2018-2024 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook to export iRMC system and hardware configuration and store
# it in a file in JSON format

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: get iRMC system and hardware configuration and store in file
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false
    # path to files to save iRMC profiles to
    #   make sure to not overwrite these files if you do not intend to
    # irmc_sysconfig_file: "Profile_SystemConfigSave.json"
    # irmc_hwconfig_file: "Profile_HWConfigurationSave.json"

  gather_facts: false

  tasks:
    # Get iRMC profiles
    - name: Get SystemConfig profile
      irmc_profiles:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "get"
        profile: "SystemConfig"
      register: system_config
      delegate_to: localhost
    - name: Get HWConfigurationIrmc profile
      irmc_profiles:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "get"
        profile: "HWConfigurationIrmc"
      register: hardware_config
      delegate_to: localhost
    - name: Show SystemConfig profile
      debug:
        msg: "{{ system_config.profile }}"
    - name: Show HWConfigurationIrmc profile
      debug:
        msg: "{{ hardware_config.profile }}"

    # Write iRMC Profiles to file
    - name: Write SystemConfig profile
      copy:
        content: "{{ system_config.profile }}"
        dest: "{{ irmc_sysconfig_file }}"
    - name: Write HWConfigurationIrmc profile
      copy:
        content: "{{ hardware_config.profile }}"
        dest: "{{ irmc_hwconfig_file }}"
