---
# Copyright 2018-2024 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook for module 'irmc_eventlog'
# to handle iRMC eventlogs

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: irmc_eventlog - usage examples
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: false

  tasks:
    # List iRMC InternalEventLog
    - block:
      - name: List iRMC InternalEventLog
        irmc_eventlog:
          irmc_url: "{{ inventory_hostname }}"
          irmc_username: "{{ irmc_user }}"
          irmc_password: "{{ irmc_password }}"
          validate_certs: "{{ validate_certificate }}"
          command: "list"
          eventlog_type: "InternalEventLog"
        delegate_to: localhost
        register: list_internaleventlog
      - name: Show list InternalEventLog
        debug:
          var: list_internaleventlog
      tags:
        - list_internaleventlog

    # List iRMC SystemEventLog
    - block:
      - name: List iRMC SystemEventLog
        irmc_eventlog:
          irmc_url: "{{ inventory_hostname }}"
          irmc_username: "{{ irmc_user }}"
          irmc_password: "{{ irmc_password }}"
          validate_certs: "{{ validate_certificate }}"
          command: "list"
          eventlog_type: "SystemEventLog"
        delegate_to: localhost
        register: list_systemeventlog
      - name: Show list SystemEventLog
        debug:
          var: list_systemeventlog
      tags:
        - list_systemeventlog
    
    # Get specific InternalEventLog entry information
    # Add '-e “id=xx”' to the command line argument of Playbook.
    - block:
      - name: Get specific InternalEventLog entry information
        irmc_eventlog:
          irmc_url: "{{ inventory_hostname }}"
          irmc_username: "{{ irmc_user }}"
          irmc_password: "{{ irmc_password }}"
          validate_certs: "{{ validate_certificate }}"
          command: "get"
          eventlog_type: "InternalEventLog"
          id: "{{ id | int }}"
        delegate_to: localhost
        register: get_internaleventlog
      - name: Show specific InternalEventLog
        debug:
          var: get_internaleventlog.eventlog_entry
      tags:
        - get_internaleventlog

    # Get specific SystemEventLog entry information
    # Add '-e “id=xx”' to the command line argument of Playbook.
    - block:
      - name: Get specific SystemEventLog entry information
        irmc_eventlog:
          irmc_url: "{{ inventory_hostname }}"
          irmc_username: "{{ irmc_user }}"
          irmc_password: "{{ irmc_password }}"
          validate_certs: "{{ validate_certificate }}"
          command: "get"
          eventlog_type: "SystemEventLog"
          id: "{{ id | int }}"
        delegate_to: localhost
        register: get_systemeventlog
      - name: Show get specific SystemEventLog
        debug:
          var: get_systemeventlog.eventlog_entry
      tags:
        - get_systemeventlog

    # Clear iRMC InternalEventLog
    - name: Clear iRMC InternalEventLog
      irmc_eventlog:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "clear"
        eventlog_type: "InternalEventLog"
      delegate_to: localhost
      tags:
        - clear_internaleventlog

    # Clear iRMC SystemEventLog
    - name: Clear iRMC SystemEventLog
      irmc_eventlog:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "clear"
        eventlog_type: "SystemEventLog"
      delegate_to: localhost
      tags:
        - clear_systemeventlog