---
# Copyright 2018-2024 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook for module 'irmc_session'
# to handle iRMC sessions

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: Usage examples for irmc_session
  connection: local
  hosts: iRMC_group

  # vars:
  #   # iRMC login credentials
  #   irmc_user: "admin"
  #   irmc_password: "admin"
  #   # Note: set validate_certificate to false for self-signed certificate
  #   validate_certificate: false

  gather_facts: false

  tasks:
    # List iRMC sessions
    - name: Get and show iRMC sessions
      tags:
        - list
      block:
        - name: List iRMC sessions
          irmc_session:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "list"
          delegate_to: localhost
          register: result
        - name: Show iRMC sessions details
          ansible.builtin.debug:
            var: result.sessions

    # Get specific session information
    - name: Get specific session information
      tags:
        - get
      block:
        - name: Get specific session information
          irmc_session:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "get"
            id: "{{ session_id | int }}"
          delegate_to: localhost
          register: result
        - name: Show specific session information
          ansible.builtin.debug:
            var: result

    # Remove specific session information
    - name: Remove specific session information
      tags:
        - remove
      block:
        - name: Remove specific session information
          irmc_session:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "remove"
            id: "{{ session_id | int }}"
          delegate_to: localhost
          register: result
        - name: Show result of remove session
          ansible.builtin.debug:
            var: result

    # Clear all sessions information
    - name: Clear all sessions information
      irmc_session:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "clearall"
      delegate_to: localhost
      register: result
      tags:
        - clearall

    # Terminate specific session
    - name: Terminate specific session
      irmc_session:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "terminate"
        id: "{{ session_id | int }}"
      delegate_to: localhost
      register: result
      tags:
        - terminate
