---
# FUJITSU LIMITED
# Copyright 2018 FUJITSU LIMITED
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook for module 'irmc_biosbootorder'
# to configure iRMC to force next boot to specified option

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: irmc_biosbootorder - usage examples
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: false

  tasks:
    # Get Bios Boot Order
    - name: Get Bios Boot Order
      fujitsu.ansible.irmc_biosbootorder:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "get"
        force_new: false
      delegate_to: localhost
    
    # Set Bios Boot Order to default
    - name: Get Bios Boot Order to default
      fujitsu.ansible.irmc_biosbootorder:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "default"
        ignore_power_on: false
      delegate_to: localhost
