---
# example playbook for module 'irmc_idled'
# to get or set server ID LED

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: irmc_idled - usage examples
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: no

  tasks:
    # Get server ID LED state
    - name: Get ID LED state
      irmc_idled:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "get"
      register: idled
      delegate_to: localhost
    - name: Show iRMC ID LED state
      debug:
        msg: "{{ idled.idled_state }}"
    
    # Set server ID LED state
    - name: Set server ID LED state
      irmc_idled:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "set"
        state: "Lit"
      delegate_to: localhost

