---
# Copyright 2018-2024 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook for module 'irmc_biosbootorder'
# to configure iRMC to force next boot to specified option

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: Usage examples for irmc_biosbootorder
  connection: local
  hosts: iRMC_group

  # vars:
  #   # iRMC login credentials
  #   irmc_user: "admin"
  #   irmc_password: "admin"
  #   # Note: set validate_certificate to false for self-signed certificate
  #   validate_certificate: false

  gather_facts: false

  tasks:
    - name: Get and show Bios Boot Order
      tags:
        - get
      block:
        - name: Get Bios Boot Order
          irmc_biosbootorder:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "get"
            force_new: "{{ force_new | default(true) }}"
          register: result
          delegate_to: localhost
        - name: Show Bios Boot Order
          ansible.builtin.debug:
            var: result.boot_order

    - name: Reset Bios Boot Order to default
      irmc_biosbootorder:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "default"
        ignore_power_on: "{{ ignore_power_on | default(false) }}"
      delegate_to: localhost
      tags:
        - reset
        - default

    - name: Set Bios Boot Order
      irmc_biosbootorder:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "set"
        boot_device: "{{ boot_device }}"
        boot_key: "{{ boot_key | default('StructuredBootString') }}"
        ignore_power_on: "{{ ignore_power_on | default(false) }}"
      delegate_to: localhost
      tags:
        - set
