---
# tasks file for ./roles/win_set_rdp

- name: Set Remote Desktop
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    type: dword
    data: "{{ enabled | ternary(0, 1) }}"
    state: present
