---
# Copyright 2018-2024 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook to set BIOS boot order to default

# Notes:
#        - this playbook will abort if the server is 'on'
#        - this playbook will cause the server to reboot a few times

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: set BIOS boot order to default
  connection: local
  hosts: iRMC_group

  vars:
    # iRMC login credentials
    # irmc_user: "admin"
    # irmc_password: "admin"
    # Note: set validate_certificate to false for self-signed certificate
    # validate_certificate: false

  gather_facts: false

  tasks:
    # Set Bios Boot Order
    - name: Set BIOS Boot Order to default
      fujitsu.primergy.irmc_biosbootorder:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "default"
        force_new: true
        ignore_power_on: false
      delegate_to: localhost
