---
# tasks file for ./roles/win_dsnap
- name: Extract the file name from path
  ansible.builtin.set_fact:
    filename: "{{ path | basename }}"

- name: Define the new parameters from vars
  ansible.builtin.set_fact:
    dsnap_src: "SVSLocalTools\\{{ language | default('English') }}\\DSNAP\\{{ cpu_arch | default('x64') }}\\dsnap.exe"
    temp_file: "{{ win_dsnap_temp }}\\{{ filename }}"

- name: Ensure the destination directory exists and copy the file from ansible control node
  block:
    - name: Create the directory for the file from ansible control node if it does not exist
      ansible.windows.win_file:
        path: "{{ win_dsnap_temp }}"
        state: directory
    - name: Copy the file from ansible control node
      ansible.windows.win_copy:
        src: "{{ path }}"
        dest: "{{ temp_file }}"

- name: Determine if the filename ends with .iso
  ansible.builtin.set_fact:
    is_iso: "{{ (filename | lower | regex_search('\\.iso$')) | ternary(True, False) }}"

- name: Mount/Unmount the iso file and copy the exe file to the temp folder
  when: is_iso
  block:
    - name: Mount the iso file
      community.windows.win_disk_image:
        image_path: "{{ temp_file }}"
        state: present
      register: mount_result
    - name: Copy dsnap.exe from the iso file to the temp folder
      ansible.windows.win_copy:
        src: "{{ mount_result.mount_paths[0] }}{{ dsnap_src }}"
        dest: "{{ win_dsnap_temp }}"
        remote_src: true
    - name: Unmount the iso file
      community.windows.win_disk_image:
        image_path: "{{ temp_file }}"
        state: absent

- name: Ensure the destination directory exists and copy dsnap.exe
  block:
    - name: Create the directory for DSNAP if it does not exist
      ansible.windows.win_file:
        path: "{{ win_dsnap_dsnap }}"
        state: directory
    - name: Copy dsnap.exe from the iso file to the created folder
      ansible.windows.win_copy:
        src: "{{ win_dsnap_exe }}"
        dest: "{{ win_dsnap_dsnap }}"
        remote_src: true

- name: Delete the temp file
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ temp_file }}"
    - "{{ win_dsnap_exe }}"
